/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lucaslui.view;

import br.com.lucaslui.logic.ExpressionSolver;
import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;

/**
 *
 * @author lucas
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initKeyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTextArea = new javax.swing.JTextArea();
        expressionTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        leftButtonPanel = new javax.swing.JPanel();
        numberSevenButton = new javax.swing.JButton();
        numberEightButton = new javax.swing.JButton();
        numberNineButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        numberFourButton = new javax.swing.JButton();
        numberFiveButton = new javax.swing.JButton();
        numberSixButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        numberOneButton = new javax.swing.JButton();
        numberTwoButton = new javax.swing.JButton();
        numberThreeButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        numberZeroButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        porcentButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        rightButtonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        leftParenthesesButton = new javax.swing.JButton();
        rightParenthesesButton = new javax.swing.JButton();
        powButton = new javax.swing.JButton();
        rootButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setName("mainFrame"); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setForeground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new java.awt.BorderLayout(0, 2));

        displayPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(262, 100));

        resultsTextArea.setEditable(false);
        resultsTextArea.setBackground(new java.awt.Color(51, 51, 51));
        resultsTextArea.setColumns(20);
        resultsTextArea.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        resultsTextArea.setForeground(new java.awt.Color(204, 204, 204));
        resultsTextArea.setLineWrap(true);
        resultsTextArea.setRows(5);
        resultsTextArea.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        resultsTextArea.setEnabled(false);
        resultsTextArea.setFocusable(false);
        jScrollPane1.setViewportView(resultsTextArea);

        displayPanel.add(jScrollPane1, java.awt.BorderLayout.NORTH);

        expressionTextField.setEditable(false);
        expressionTextField.setBackground(new java.awt.Color(51, 51, 51));
        expressionTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        expressionTextField.setForeground(new java.awt.Color(204, 204, 204));
        expressionTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expressionTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        expressionTextField.setEnabled(false);
        expressionTextField.setFocusable(false);
        expressionTextField.setPreferredSize(new java.awt.Dimension(114, 40));
        displayPanel.add(expressionTextField, java.awt.BorderLayout.CENTER);

        mainPanel.add(displayPanel, java.awt.BorderLayout.NORTH);

        buttonPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonPanel.setForeground(new java.awt.Color(204, 204, 204));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftButtonPanel.setBackground(new java.awt.Color(51, 51, 51));
        leftButtonPanel.setForeground(new java.awt.Color(204, 204, 204));
        leftButtonPanel.setLayout(new java.awt.GridLayout(4, 6, 3, 3));

        numberSevenButton.setBackground(new java.awt.Color(51, 51, 51));
        numberSevenButton.setForeground(new java.awt.Color(204, 204, 204));
        numberSevenButton.setText("7");
        numberSevenButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberSevenButton.setFocusable(false);
        numberSevenButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberSevenButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberSevenButton.setOpaque(true);
        numberSevenButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberSevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberSevenButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberSevenButton);

        numberEightButton.setBackground(new java.awt.Color(51, 51, 51));
        numberEightButton.setForeground(new java.awt.Color(204, 204, 204));
        numberEightButton.setText("8");
        numberEightButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberEightButton.setFocusable(false);
        numberEightButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberEightButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberEightButton.setOpaque(true);
        numberEightButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberEightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberEightButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberEightButton);

        numberNineButton.setBackground(new java.awt.Color(51, 51, 51));
        numberNineButton.setForeground(new java.awt.Color(204, 204, 204));
        numberNineButton.setText("9");
        numberNineButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberNineButton.setFocusable(false);
        numberNineButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberNineButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberNineButton.setOpaque(true);
        numberNineButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberNineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberNineButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberNineButton);

        divisionButton.setBackground(new java.awt.Color(51, 51, 51));
        divisionButton.setForeground(new java.awt.Color(204, 204, 204));
        divisionButton.setText("/");
        divisionButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        divisionButton.setFocusable(false);
        divisionButton.setMaximumSize(new java.awt.Dimension(20, 20));
        divisionButton.setMinimumSize(new java.awt.Dimension(20, 20));
        divisionButton.setOpaque(true);
        divisionButton.setPreferredSize(new java.awt.Dimension(20, 20));
        divisionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(divisionButton);

        numberFourButton.setBackground(new java.awt.Color(51, 51, 51));
        numberFourButton.setForeground(new java.awt.Color(204, 204, 204));
        numberFourButton.setText("4");
        numberFourButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberFourButton.setFocusable(false);
        numberFourButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberFourButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberFourButton.setOpaque(true);
        numberFourButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberFourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberFourButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberFourButton);

        numberFiveButton.setBackground(new java.awt.Color(51, 51, 51));
        numberFiveButton.setForeground(new java.awt.Color(204, 204, 204));
        numberFiveButton.setText("5");
        numberFiveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberFiveButton.setFocusable(false);
        numberFiveButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberFiveButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberFiveButton.setOpaque(true);
        numberFiveButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberFiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberFiveButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberFiveButton);

        numberSixButton.setBackground(new java.awt.Color(51, 51, 51));
        numberSixButton.setForeground(new java.awt.Color(204, 204, 204));
        numberSixButton.setText("6");
        numberSixButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberSixButton.setFocusable(false);
        numberSixButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberSixButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberSixButton.setOpaque(true);
        numberSixButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberSixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberSixButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberSixButton);

        multiplyButton.setBackground(new java.awt.Color(51, 51, 51));
        multiplyButton.setForeground(new java.awt.Color(204, 204, 204));
        multiplyButton.setText("*");
        multiplyButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        multiplyButton.setFocusable(false);
        multiplyButton.setMaximumSize(new java.awt.Dimension(20, 20));
        multiplyButton.setMinimumSize(new java.awt.Dimension(20, 20));
        multiplyButton.setOpaque(true);
        multiplyButton.setPreferredSize(new java.awt.Dimension(20, 20));
        multiplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(multiplyButton);

        numberOneButton.setBackground(new java.awt.Color(51, 51, 51));
        numberOneButton.setForeground(new java.awt.Color(204, 204, 204));
        numberOneButton.setText("1");
        numberOneButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberOneButton.setFocusable(false);
        numberOneButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberOneButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberOneButton.setOpaque(true);
        numberOneButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneButtonActionPerformed(evt);
            }
        });
        leftButtonPanel.add(numberOneButton);

        numberTwoButton.setBackground(new java.awt.Color(51, 51, 51));
        numberTwoButton.setForeground(new java.awt.Color(204, 204, 204));
        numberTwoButton.setText("2");
        numberTwoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberTwoButton.setFocusable(false);
        numberTwoButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberTwoButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberTwoButton.setOpaque(true);
        numberTwoButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberTwoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberTwoButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberTwoButton);

        numberThreeButton.setBackground(new java.awt.Color(51, 51, 51));
        numberThreeButton.setForeground(new java.awt.Color(204, 204, 204));
        numberThreeButton.setText("3");
        numberThreeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberThreeButton.setFocusable(false);
        numberThreeButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberThreeButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberThreeButton.setOpaque(true);
        numberThreeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberThreeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberThreeButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberThreeButton);

        minusButton.setBackground(new java.awt.Color(51, 51, 51));
        minusButton.setForeground(new java.awt.Color(204, 204, 204));
        minusButton.setText("-");
        minusButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        minusButton.setFocusable(false);
        minusButton.setMaximumSize(new java.awt.Dimension(20, 20));
        minusButton.setMinimumSize(new java.awt.Dimension(20, 20));
        minusButton.setOpaque(true);
        minusButton.setPreferredSize(new java.awt.Dimension(20, 20));
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(minusButton);

        numberZeroButton.setBackground(new java.awt.Color(51, 51, 51));
        numberZeroButton.setForeground(new java.awt.Color(204, 204, 204));
        numberZeroButton.setText("0");
        numberZeroButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        numberZeroButton.setFocusable(false);
        numberZeroButton.setMaximumSize(new java.awt.Dimension(20, 20));
        numberZeroButton.setMinimumSize(new java.awt.Dimension(20, 20));
        numberZeroButton.setOpaque(true);
        numberZeroButton.setPreferredSize(new java.awt.Dimension(20, 20));
        numberZeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberZeroButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(numberZeroButton);

        dotButton.setBackground(new java.awt.Color(51, 51, 51));
        dotButton.setForeground(new java.awt.Color(204, 204, 204));
        dotButton.setText(".");
        dotButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        dotButton.setFocusable(false);
        dotButton.setMaximumSize(new java.awt.Dimension(20, 20));
        dotButton.setMinimumSize(new java.awt.Dimension(20, 20));
        dotButton.setOpaque(true);
        dotButton.setPreferredSize(new java.awt.Dimension(20, 20));
        dotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(dotButton);

        porcentButton.setBackground(new java.awt.Color(51, 51, 51));
        porcentButton.setForeground(new java.awt.Color(204, 204, 204));
        porcentButton.setText("%");
        porcentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        porcentButton.setFocusable(false);
        porcentButton.setMaximumSize(new java.awt.Dimension(20, 20));
        porcentButton.setMinimumSize(new java.awt.Dimension(20, 20));
        porcentButton.setOpaque(true);
        porcentButton.setPreferredSize(new java.awt.Dimension(20, 20));
        leftButtonPanel.add(porcentButton);

        plusButton.setBackground(new java.awt.Color(51, 51, 51));
        plusButton.setForeground(new java.awt.Color(204, 204, 204));
        plusButton.setText("+");
        plusButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        plusButton.setFocusable(false);
        plusButton.setMaximumSize(new java.awt.Dimension(20, 20));
        plusButton.setMinimumSize(new java.awt.Dimension(20, 20));
        plusButton.setOpaque(true);
        plusButton.setPreferredSize(new java.awt.Dimension(20, 20));
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusButtonMouseClicked(evt);
            }
        });
        leftButtonPanel.add(plusButton);

        buttonPanel.add(leftButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 216, 214));

        rightButtonPanel.setBackground(new java.awt.Color(51, 51, 51));
        rightButtonPanel.setForeground(new java.awt.Color(204, 204, 204));
        rightButtonPanel.setLayout(new java.awt.GridLayout(3, 2, 3, 3));

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(204, 204, 204));
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        backButton.setFocusable(false);
        backButton.setMaximumSize(new java.awt.Dimension(20, 20));
        backButton.setMinimumSize(new java.awt.Dimension(20, 20));
        backButton.setOpaque(true);
        backButton.setPreferredSize(new java.awt.Dimension(20, 20));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        rightButtonPanel.add(backButton);

        clearButton.setBackground(new java.awt.Color(51, 51, 51));
        clearButton.setForeground(new java.awt.Color(204, 204, 204));
        clearButton.setText("Clear");
        clearButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        clearButton.setFocusable(false);
        clearButton.setMaximumSize(new java.awt.Dimension(20, 20));
        clearButton.setMinimumSize(new java.awt.Dimension(20, 20));
        clearButton.setOpaque(true);
        clearButton.setPreferredSize(new java.awt.Dimension(20, 20));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        rightButtonPanel.add(clearButton);

        leftParenthesesButton.setBackground(new java.awt.Color(51, 51, 51));
        leftParenthesesButton.setForeground(new java.awt.Color(204, 204, 204));
        leftParenthesesButton.setText("(");
        leftParenthesesButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        leftParenthesesButton.setFocusable(false);
        leftParenthesesButton.setMaximumSize(new java.awt.Dimension(20, 20));
        leftParenthesesButton.setMinimumSize(new java.awt.Dimension(20, 20));
        leftParenthesesButton.setOpaque(true);
        leftParenthesesButton.setPreferredSize(new java.awt.Dimension(20, 20));
        leftParenthesesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftParenthesesButtonMouseClicked(evt);
            }
        });
        rightButtonPanel.add(leftParenthesesButton);

        rightParenthesesButton.setBackground(new java.awt.Color(51, 51, 51));
        rightParenthesesButton.setForeground(new java.awt.Color(204, 204, 204));
        rightParenthesesButton.setText(")");
        rightParenthesesButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        rightParenthesesButton.setFocusable(false);
        rightParenthesesButton.setMaximumSize(new java.awt.Dimension(20, 20));
        rightParenthesesButton.setMinimumSize(new java.awt.Dimension(20, 20));
        rightParenthesesButton.setOpaque(true);
        rightParenthesesButton.setPreferredSize(new java.awt.Dimension(20, 20));
        rightParenthesesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightParenthesesButtonMouseClicked(evt);
            }
        });
        rightButtonPanel.add(rightParenthesesButton);

        powButton.setBackground(new java.awt.Color(51, 51, 51));
        powButton.setForeground(new java.awt.Color(204, 204, 204));
        powButton.setText("^");
        powButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        powButton.setFocusable(false);
        powButton.setMaximumSize(new java.awt.Dimension(20, 20));
        powButton.setMinimumSize(new java.awt.Dimension(20, 20));
        powButton.setOpaque(true);
        powButton.setPreferredSize(new java.awt.Dimension(20, 20));
        powButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                powButtonMouseClicked(evt);
            }
        });
        rightButtonPanel.add(powButton);

        rootButton.setBackground(new java.awt.Color(51, 51, 51));
        rootButton.setForeground(new java.awt.Color(204, 204, 204));
        rootButton.setText("Root");
        rootButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        rootButton.setFocusable(false);
        rootButton.setMaximumSize(new java.awt.Dimension(20, 20));
        rootButton.setMinimumSize(new java.awt.Dimension(20, 20));
        rootButton.setOpaque(true);
        rootButton.setPreferredSize(new java.awt.Dimension(20, 20));
        rootButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rootButtonMouseClicked(evt);
            }
        });
        rightButtonPanel.add(rootButton);

        buttonPanel.add(rightButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 108, 162));

        equalButton.setBackground(new java.awt.Color(51, 51, 51));
        equalButton.setForeground(new java.awt.Color(204, 204, 204));
        equalButton.setText("=");
        equalButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        equalButton.setFocusable(false);
        equalButton.setOpaque(true);
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(equalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 166, 104, 48));

        mainPanel.add(buttonPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initKeyComponents() {

        InputMap inputMap = mainPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMap.put(KeyStroke.getKeyStroke('1'), "addNumberOneToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('2'), "addNumberTwoToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('3'), "addNumberThreeToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('4'), "addNumberFourToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('5'), "addNumberFiveToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('6'), "addNumberSixToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('7'), "addNumberSevenToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('8'), "addNumberEightToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('9'), "addNumberNineToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('0'), "addNumberZeroToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('/'), "addOperatorDivisionToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('*'), "addOperatorMultiplyToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('-'), "addOperatorMinusToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('+'), "addOperatorPlusToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('.'), "addOperatorDotToDisplay");
        inputMap.put(KeyStroke.getKeyStroke(','), "addOperatorDotToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('='), "solveExpression");
        inputMap.put(KeyStroke.getKeyStroke("ENTER"), "solveExpression");
        inputMap.put(KeyStroke.getKeyStroke("BACK_SPACE"), "backspaceExpression");

        ActionMap actionMap = mainPanel.getActionMap();

        actionMap.put("addNumberOneToDisplay", new KeyActionBinding("1"));
        actionMap.put("addNumberTwoToDisplay", new KeyActionBinding("2"));
        actionMap.put("addNumberThreeToDisplay", new KeyActionBinding("3"));
        actionMap.put("addNumberFourToDisplay", new KeyActionBinding("4"));
        actionMap.put("addNumberFiveToDisplay", new KeyActionBinding("5"));
        actionMap.put("addNumberSixToDisplay", new KeyActionBinding("6"));
        actionMap.put("addNumberSevenToDisplay", new KeyActionBinding("7"));
        actionMap.put("addNumberEightToDisplay", new KeyActionBinding("8"));
        actionMap.put("addNumberNineToDisplay", new KeyActionBinding("9"));
        actionMap.put("addNumberZeroToDisplay", new KeyActionBinding("0"));
        actionMap.put("addOperatorDivisionToDisplay", new KeyActionBinding("/"));
        actionMap.put("addOperatorMultiplyToDisplay", new KeyActionBinding("*"));
        actionMap.put("addOperatorMinusToDisplay", new KeyActionBinding("-"));
        actionMap.put("addOperatorPlusToDisplay", new KeyActionBinding("+"));
        actionMap.put("addOperatorDotToDisplay", new KeyActionBinding("."));
        actionMap.put("solveExpression", new SolverActionBinding());
        actionMap.put("backspaceExpression", new BackspaceActionBinding());
    }

    private class KeyActionBinding extends AbstractAction {

        public KeyActionBinding(String name) {
            super(name);
        }

        @Override
        public void actionPerformed(ActionEvent evt) {
            addCharacterToDisplay(this.getValue(Action.NAME).toString());
        }
    }

    private class SolverActionBinding extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent evt) {
            solveExpression();
        }
    }

    private class BackspaceActionBinding extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent evt) {
            backspaceExpression();
        }
    }

    private void solveExpression() {

        String expression = expressionTextField.getText();
        if (expression != null) {
            try {
                Double result = ExpressionSolver.evaluate(expression);
                resultsTextArea.append(expression + "=" + result.toString() + "\n");
                clearExpression();
            } catch (java.util.EmptyStackException | IllegalArgumentException e) {
                resultsTextArea.append("Expression Wrong\n");
            }
        }
    }

    private void clearExpression() {
        expressionTextField.setText("");
    }

    private void backspaceExpression() {
        String expression = expressionTextField.getText();
        if (expression != null && expression.length() > 0) {
            expressionTextField.setText(expression.substring(0, expression.length() - 1));
        }
    }

    private void addCharacterToDisplay(String number) {
        expressionTextField.setText(expressionTextField.getText() + number);
    }

    private void numberOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneButtonActionPerformed
        addCharacterToDisplay("1");
    }//GEN-LAST:event_numberOneButtonActionPerformed

    private void numberTwoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberTwoButtonMouseClicked
        addCharacterToDisplay("2");
    }//GEN-LAST:event_numberTwoButtonMouseClicked

    private void numberThreeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberThreeButtonMouseClicked
        addCharacterToDisplay("3");
    }//GEN-LAST:event_numberThreeButtonMouseClicked

    private void numberFourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberFourButtonMouseClicked
        addCharacterToDisplay("4");
    }//GEN-LAST:event_numberFourButtonMouseClicked

    private void numberFiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberFiveButtonMouseClicked
        addCharacterToDisplay("5");
    }//GEN-LAST:event_numberFiveButtonMouseClicked

    private void numberSixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberSixButtonMouseClicked
        addCharacterToDisplay("6");
    }//GEN-LAST:event_numberSixButtonMouseClicked

    private void numberSevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberSevenButtonMouseClicked
        addCharacterToDisplay("7");
    }//GEN-LAST:event_numberSevenButtonMouseClicked

    private void numberEightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberEightButtonMouseClicked
        addCharacterToDisplay("8");
    }//GEN-LAST:event_numberEightButtonMouseClicked

    private void numberNineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberNineButtonMouseClicked
        addCharacterToDisplay("9");
    }//GEN-LAST:event_numberNineButtonMouseClicked

    private void numberZeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberZeroButtonMouseClicked
        addCharacterToDisplay("0");
    }//GEN-LAST:event_numberZeroButtonMouseClicked

    private void divisionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionButtonMouseClicked
        addCharacterToDisplay("/");
    }//GEN-LAST:event_divisionButtonMouseClicked

    private void multiplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyButtonMouseClicked
        addCharacterToDisplay("*");
    }//GEN-LAST:event_multiplyButtonMouseClicked

    private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked
        addCharacterToDisplay("-");
    }//GEN-LAST:event_minusButtonMouseClicked

    private void plusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseClicked
        addCharacterToDisplay("+");
    }//GEN-LAST:event_plusButtonMouseClicked

    private void dotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotButtonMouseClicked
        addCharacterToDisplay(".");
    }//GEN-LAST:event_dotButtonMouseClicked

    private void equalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseClicked
        solveExpression();
    }//GEN-LAST:event_equalButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        clearExpression();
    }//GEN-LAST:event_clearButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        backspaceExpression();
    }//GEN-LAST:event_backButtonMouseClicked

    private void leftParenthesesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftParenthesesButtonMouseClicked
        addCharacterToDisplay("(");
    }//GEN-LAST:event_leftParenthesesButtonMouseClicked

    private void rightParenthesesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightParenthesesButtonMouseClicked
        addCharacterToDisplay(")");
    }//GEN-LAST:event_rightParenthesesButtonMouseClicked

    private void powButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powButtonMouseClicked
        addCharacterToDisplay("^");
    }//GEN-LAST:event_powButtonMouseClicked

    private void rootButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootButtonMouseClicked
        addCharacterToDisplay("");
    }//GEN-LAST:event_rootButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JTextField expressionTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftButtonPanel;
    private javax.swing.JButton leftParenthesesButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton numberEightButton;
    private javax.swing.JButton numberFiveButton;
    private javax.swing.JButton numberFourButton;
    private javax.swing.JButton numberNineButton;
    private javax.swing.JButton numberOneButton;
    private javax.swing.JButton numberSevenButton;
    private javax.swing.JButton numberSixButton;
    private javax.swing.JButton numberThreeButton;
    private javax.swing.JButton numberTwoButton;
    private javax.swing.JButton numberZeroButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton porcentButton;
    private javax.swing.JButton powButton;
    private javax.swing.JTextArea resultsTextArea;
    private javax.swing.JPanel rightButtonPanel;
    private javax.swing.JButton rightParenthesesButton;
    private javax.swing.JButton rootButton;
    // End of variables declaration//GEN-END:variables
}
