/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lucaslui.view;

import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;


/**
 *
 * @author lucas
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initKeyComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        displayTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        numberOneButton = new javax.swing.JButton();
        numberTwoButton = new javax.swing.JButton();
        numberThreeButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        numberFourButton = new javax.swing.JButton();
        numberFiveButton = new javax.swing.JButton();
        numberSixButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        numberSevenButton = new javax.swing.JButton();
        numberEightButton = new javax.swing.JButton();
        numberNineButton = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        numberZeroButton = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setName("mainFrame"); // NOI18N
        setResizable(false);

        mainPanel.setLayout(new java.awt.BorderLayout(3, 3));

        displayTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        displayTextField.setEnabled(false);
        displayTextField.setPreferredSize(new java.awt.Dimension(114, 100));
        mainPanel.add(displayTextField, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setLayout(new java.awt.GridLayout(4, 4, 3, 3));

        numberOneButton.setText("1");
        numberOneButton.setFocusable(false);
        numberOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(numberOneButton);

        numberTwoButton.setText("2");
        numberTwoButton.setFocusable(false);
        numberTwoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberTwoButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberTwoButton);

        numberThreeButton.setText("3");
        numberThreeButton.setFocusable(false);
        numberThreeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberThreeButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberThreeButton);

        divisionButton.setText("/");
        divisionButton.setFocusable(false);
        buttonPanel.add(divisionButton);

        numberFourButton.setText("4");
        numberFourButton.setFocusable(false);
        numberFourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberFourButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberFourButton);

        numberFiveButton.setText("5");
        numberFiveButton.setFocusable(false);
        numberFiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberFiveButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberFiveButton);

        numberSixButton.setText("6");
        numberSixButton.setFocusable(false);
        numberSixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberSixButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberSixButton);

        multiplyButton.setText("*");
        multiplyButton.setFocusable(false);
        buttonPanel.add(multiplyButton);

        numberSevenButton.setText("7");
        numberSevenButton.setFocusable(false);
        numberSevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberSevenButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberSevenButton);

        numberEightButton.setText("8");
        numberEightButton.setFocusable(false);
        numberEightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberEightButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberEightButton);

        numberNineButton.setText("9");
        numberNineButton.setFocusable(false);
        numberNineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberNineButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberNineButton);

        jButton12.setText("-");
        jButton12.setFocusable(false);
        buttonPanel.add(jButton12);

        numberZeroButton.setText("0");
        numberZeroButton.setFocusable(false);
        numberZeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberZeroButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(numberZeroButton);

        jButton14.setText("-");
        jButton14.setFocusable(false);
        buttonPanel.add(jButton14);

        jButton15.setText("=");
        jButton15.setFocusable(false);
        buttonPanel.add(jButton15);

        jButton16.setText("+");
        jButton16.setFocusable(false);
        buttonPanel.add(jButton16);

        mainPanel.add(buttonPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initKeyComponents(){
        
        InputMap inputMap = mainPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        inputMap.put(KeyStroke.getKeyStroke('1'), "addNumberOneToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('2'), "addNumberTwoToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('3'), "addNumberThreeToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('4'), "addNumberFourToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('5'), "addNumberFiveToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('6'), "addNumberSixToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('7'), "addNumberSevenToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('8'), "addNumberEightToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('9'), "addNumberNineToDisplay");
        inputMap.put(KeyStroke.getKeyStroke('0'), "addNumberZeroToDisplay");
        
        ActionMap actionMap = mainPanel.getActionMap();
        
        actionMap.put("addNumberOneToDisplay", new KeyActionBinding("1")); 
        actionMap.put("addNumberTwoToDisplay", new KeyActionBinding("2"));
        actionMap.put("addNumberThreeToDisplay", new KeyActionBinding("3"));
        actionMap.put("addNumberFourToDisplay", new KeyActionBinding("4"));
        actionMap.put("addNumberFiveToDisplay", new KeyActionBinding("5"));
        actionMap.put("addNumberSixToDisplay", new KeyActionBinding("6"));
        actionMap.put("addNumberSevenToDisplay", new KeyActionBinding("7"));
        actionMap.put("addNumberEightToDisplay", new KeyActionBinding("8"));
        actionMap.put("addNumberNineToDisplay", new KeyActionBinding("9"));
        actionMap.put("addNumberZeroToDisplay", new KeyActionBinding("0"));
    }
        
    private class KeyActionBinding extends AbstractAction{

        public KeyActionBinding(String name) {
            super(name);
        }
        
        @Override
        public void actionPerformed(ActionEvent evt) {
             AddNumberToDisplayFromMouseCliked(this.getValue(Action.NAME).toString());
        }        
    }
    
    private void AddNumberToDisplayFromMouseCliked(String number){
        displayTextField.setText(displayTextField.getText() + number);
    }
     
    private void numberOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneButtonActionPerformed
        AddNumberToDisplayFromMouseCliked("1");
    }//GEN-LAST:event_numberOneButtonActionPerformed

    private void numberTwoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberTwoButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("2");
    }//GEN-LAST:event_numberTwoButtonMouseClicked

    private void numberThreeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberThreeButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("3");
    }//GEN-LAST:event_numberThreeButtonMouseClicked

    private void numberFourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberFourButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("4");
    }//GEN-LAST:event_numberFourButtonMouseClicked

    private void numberFiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberFiveButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("5");
    }//GEN-LAST:event_numberFiveButtonMouseClicked

    private void numberSixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberSixButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("6");
    }//GEN-LAST:event_numberSixButtonMouseClicked

    private void numberSevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberSevenButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("7");
    }//GEN-LAST:event_numberSevenButtonMouseClicked

    private void numberEightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberEightButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("8");
    }//GEN-LAST:event_numberEightButtonMouseClicked

    private void numberNineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberNineButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("9");
    }//GEN-LAST:event_numberNineButtonMouseClicked

    private void numberZeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberZeroButtonMouseClicked
        AddNumberToDisplayFromMouseCliked("0");
    }//GEN-LAST:event_numberZeroButtonMouseClicked
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton numberEightButton;
    private javax.swing.JButton numberFiveButton;
    private javax.swing.JButton numberFourButton;
    private javax.swing.JButton numberNineButton;
    private javax.swing.JButton numberOneButton;
    private javax.swing.JButton numberSevenButton;
    private javax.swing.JButton numberSixButton;
    private javax.swing.JButton numberThreeButton;
    private javax.swing.JButton numberTwoButton;
    private javax.swing.JButton numberZeroButton;
    // End of variables declaration//GEN-END:variables
}
