/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lucaslui.view;

/**
 *
 * @author lucas
 */
public class ProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfileFrame
     */
    public ProfileFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftjPanel = new javax.swing.JPanel();
        photojLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        varNamejLabel = new javax.swing.JLabel();
        varGenrejLabel = new javax.swing.JLabel();
        varPhonejLabel = new javax.swing.JLabel();
        logoutIconjLabel = new javax.swing.JLabel();
        logoutjLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        topjPanel = new javax.swing.JPanel();
        chatListjLabel = new javax.swing.JLabel();
        friendListjLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        centerjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendlistjList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatlistjList = new javax.swing.JList<>();
        addFriendjButton = new javax.swing.JButton();
        removeFriendjButton = new javax.swing.JButton();
        openChatjButton = new javax.swing.JButton();
        eraseChatjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela de Perfil do Usuário");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftjPanel.setBackground(new java.awt.Color(0, 102, 255));

        photojLabel.setBackground(new java.awt.Color(255, 255, 255));
        photojLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        photojLabel.setForeground(new java.awt.Color(255, 255, 255));
        photojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/user-photo-130.png"))); // NOI18N
        photojLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Fira Sans Book", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Fira Sans Book", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Idade");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Fira Sans Book", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Gênero");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        varNamejLabel.setBackground(new java.awt.Color(255, 255, 255));
        varNamejLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        varNamejLabel.setForeground(new java.awt.Color(255, 255, 255));

        varGenrejLabel.setBackground(new java.awt.Color(255, 255, 255));
        varGenrejLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        varGenrejLabel.setForeground(new java.awt.Color(255, 255, 255));

        varPhonejLabel.setBackground(new java.awt.Color(255, 255, 255));
        varPhonejLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        varPhonejLabel.setForeground(new java.awt.Color(255, 255, 255));

        logoutIconjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutIconjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/Logout-25.png"))); // NOI18N
        logoutIconjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutIconjLabelMouseClicked(evt);
            }
        });

        logoutjLabel.setBackground(new java.awt.Color(255, 255, 255));
        logoutjLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        logoutjLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutjLabel.setText("Sair");
        logoutjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutjLabelMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout leftjPanelLayout = new javax.swing.GroupLayout(leftjPanel);
        leftjPanel.setLayout(leftjPanelLayout);
        leftjPanelLayout.setHorizontalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftjPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(varNamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varPhonejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varGenrejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftjPanelLayout.createSequentialGroup()
                        .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(leftjPanelLayout.createSequentialGroup()
                                    .addComponent(logoutIconjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(logoutjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(photojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftjPanelLayout.setVerticalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(photojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(varNamejLabel))
                .addGap(18, 18, 18)
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(varPhonejLabel))
                .addGap(18, 18, 18)
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(varGenrejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutIconjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(leftjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 186, 526));

        topjPanel.setBackground(new java.awt.Color(0, 0, 204));

        chatListjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chatListjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/chat-list.png"))); // NOI18N

        friendListjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friendListjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/User Group-64.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Fira Sans Book", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lista de Amigos");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Fira Sans Book", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lista de Conversas");

        javax.swing.GroupLayout topjPanelLayout = new javax.swing.GroupLayout(topjPanel);
        topjPanel.setLayout(topjPanelLayout);
        topjPanelLayout.setHorizontalGroup(
            topjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topjPanelLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(topjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topjPanelLayout.createSequentialGroup()
                        .addComponent(friendListjLabel)
                        .addGap(197, 197, 197)
                        .addComponent(chatListjLabel)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        topjPanelLayout.setVerticalGroup(
            topjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(friendListjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatListjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(topjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-19, -2, 808, 130));

        centerjPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerjPanel.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        friendlistjList.setBackground(new java.awt.Color(255, 255, 255));
        friendlistjList.setFont(new java.awt.Font("Fira Sans Book", 0, 16)); // NOI18N
        friendlistjList.setForeground(new java.awt.Color(0, 0, 0));
        friendlistjList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(friendlistjList);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));

        chatlistjList.setBackground(new java.awt.Color(255, 255, 255));
        chatlistjList.setFont(new java.awt.Font("Fira Sans Book", 0, 16)); // NOI18N
        chatlistjList.setForeground(new java.awt.Color(0, 0, 0));
        chatlistjList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(chatlistjList);

        addFriendjButton.setBackground(new java.awt.Color(0, 51, 255));
        addFriendjButton.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        addFriendjButton.setForeground(new java.awt.Color(255, 255, 255));
        addFriendjButton.setText("Adicionar");
        addFriendjButton.setBorder(null);
        addFriendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendjButtonActionPerformed(evt);
            }
        });

        removeFriendjButton.setBackground(new java.awt.Color(0, 51, 255));
        removeFriendjButton.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        removeFriendjButton.setForeground(new java.awt.Color(255, 255, 255));
        removeFriendjButton.setText("Remover");
        removeFriendjButton.setBorder(null);

        openChatjButton.setBackground(new java.awt.Color(0, 51, 255));
        openChatjButton.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        openChatjButton.setForeground(new java.awt.Color(255, 255, 255));
        openChatjButton.setText("Abrir");
        openChatjButton.setBorder(null);
        openChatjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openChatjButtonActionPerformed(evt);
            }
        });

        eraseChatjButton.setBackground(new java.awt.Color(0, 51, 255));
        eraseChatjButton.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        eraseChatjButton.setForeground(new java.awt.Color(255, 255, 255));
        eraseChatjButton.setText("Apagar");
        eraseChatjButton.setBorder(null);

        javax.swing.GroupLayout centerjPanelLayout = new javax.swing.GroupLayout(centerjPanel);
        centerjPanel.setLayout(centerjPanelLayout);
        centerjPanelLayout.setHorizontalGroup(
            centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerjPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centerjPanelLayout.createSequentialGroup()
                        .addComponent(removeFriendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFriendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centerjPanelLayout.createSequentialGroup()
                        .addComponent(eraseChatjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openChatjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        centerjPanelLayout.setVerticalGroup(
            centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerjPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addFriendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(removeFriendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(openChatjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eraseChatjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        getContentPane().add(centerjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 110, 616, 416));

        setSize(new java.awt.Dimension(759, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openChatjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openChatjButtonActionPerformed
        new ChatFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_openChatjButtonActionPerformed

    private void addFriendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendjButtonActionPerformed
        new AddFriendDialog(this,rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_addFriendjButtonActionPerformed

    private void logoutIconjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutIconjLabelMouseClicked
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutIconjLabelMouseClicked

    private void logoutjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutjLabelMouseClicked
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutjLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriendjButton;
    private javax.swing.JPanel centerjPanel;
    private javax.swing.JLabel chatListjLabel;
    private javax.swing.JList<String> chatlistjList;
    private javax.swing.JButton eraseChatjButton;
    private javax.swing.JLabel friendListjLabel;
    private javax.swing.JList<String> friendlistjList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel leftjPanel;
    private javax.swing.JLabel logoutIconjLabel;
    private javax.swing.JLabel logoutjLabel;
    private javax.swing.JButton openChatjButton;
    private javax.swing.JLabel photojLabel;
    private javax.swing.JButton removeFriendjButton;
    private javax.swing.JPanel topjPanel;
    private javax.swing.JLabel varGenrejLabel;
    private javax.swing.JLabel varNamejLabel;
    private javax.swing.JLabel varPhonejLabel;
    // End of variables declaration//GEN-END:variables
}
