/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lucaslui.view;

import br.com.lucaslui.logic.Communication;
import javax.swing.JTextArea;

/**
 *
 * @author lucas
 */
public class ChatFrame extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form ChatFrame
     */
    public ChatFrame() {
        initComponents();
        chatUpdateThread = new Thread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        destPhotojLabel = new javax.swing.JLabel();
        destNamejLabel = new javax.swing.JLabel();
        remetNamejLabel = new javax.swing.JLabel();
        remetPhotojLabel = new javax.swing.JLabel();
        sendMessagejButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagejTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatjTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Janela de Conversa");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        topPanel.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setForeground(new java.awt.Color(0, 0, 0));

        destPhotojLabel.setBackground(new java.awt.Color(255, 255, 255));
        destPhotojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destPhotojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/user-photo.png"))); // NOI18N
        destPhotojLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        destPhotojLabel.setFocusable(false);

        destNamejLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        destNamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destNamejLabel.setText("Destinatário");
        destNamejLabel.setFocusable(false);

        remetNamejLabel.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        remetNamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remetNamejLabel.setText("Remetente");
        remetNamejLabel.setFocusable(false);

        remetPhotojLabel.setBackground(new java.awt.Color(255, 255, 255));
        remetPhotojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remetPhotojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/user-photo.png"))); // NOI18N
        remetPhotojLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        remetPhotojLabel.setFocusable(false);

        sendMessagejButton.setBackground(new java.awt.Color(0, 51, 255));
        sendMessagejButton.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        sendMessagejButton.setForeground(new java.awt.Color(255, 255, 255));
        sendMessagejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lucaslui/imgs/send.png"))); // NOI18N
        sendMessagejButton.setText("Enviar");
        sendMessagejButton.setBorder(null);
        sendMessagejButton.setFocusable(false);
        sendMessagejButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sendMessagejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessagejButtonActionPerformed(evt);
            }
        });

        messagejTextArea.setBackground(new java.awt.Color(215, 215, 215));
        messagejTextArea.setColumns(20);
        messagejTextArea.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        messagejTextArea.setForeground(new java.awt.Color(0, 0, 0));
        messagejTextArea.setRows(5);
        messagejTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        messagejTextArea.setCaretColor(new java.awt.Color(0, 0, 0));
        messagejTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        messagejTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        messagejTextArea.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jScrollPane1.setViewportView(messagejTextArea);

        chatjTextArea.setBackground(new java.awt.Color(215, 215, 215));
        chatjTextArea.setColumns(20);
        chatjTextArea.setFont(new java.awt.Font("Fira Sans Book", 0, 18)); // NOI18N
        chatjTextArea.setForeground(new java.awt.Color(0, 0, 0));
        chatjTextArea.setRows(5);
        chatjTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chatjTextArea.setCaretColor(new java.awt.Color(0, 0, 0));
        chatjTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        chatjTextArea.setEnabled(false);
        chatjTextArea.setFocusable(false);
        chatjTextArea.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jScrollPane2.setViewportView(chatjTextArea);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(centerPanelLayout.createSequentialGroup()
                                .addComponent(remetNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(destNamejLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(destPhotojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane2))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(remetPhotojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendMessagejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(destPhotojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destNamejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remetNamejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendMessagejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(remetPhotojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(centerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new ProfileFrame().setVisible(true);
        chatUpdateThread.interrupt(); 
    }//GEN-LAST:event_formWindowClosed

    private void sendMessagejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessagejButtonActionPerformed
        String message = messagejTextArea.getText();
        new Communication().sendMessage(message);
    }//GEN-LAST:event_sendMessagejButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        chatUpdateThread.start();
    }//GEN-LAST:event_formWindowOpened

    @Override
    public void run() {
        new Communication().receiveMessage(chatjTextArea);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextArea chatjTextArea;
    private javax.swing.JLabel destNamejLabel;
    private javax.swing.JLabel destPhotojLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messagejTextArea;
    private javax.swing.JLabel remetNamejLabel;
    private javax.swing.JLabel remetPhotojLabel;
    private javax.swing.JButton sendMessagejButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
    
    private Thread chatUpdateThread;
}
